# Generated by Django 4.0.4 on 2022-04-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EIBData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financedproject',
            name='signed_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
